{
 "title": "Docker monitoring",
 "description": "Docker monitoring with Prometheus and cAdvisor",
 "tags": [ "docker" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(container_last_seen, job)"
    }
   },
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(container_last_seen{job=~\"$job\"}, host)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(container_last_seen{job=~\"$job\",host=~\"$host\"}, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Running containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{job=~\"$job\",host=~\"$host\",name=~\"$container\",name!=\"\"})"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{job=~\"$job\",host=~\"$host\",name=~\"$container\",name!=\"\"})/1024/1024"
    }
   ]
  },
  {
   "title": "Total CPU Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{job=~\"$job\",host=~\"$host\",name=~\"$container\",name!=\"\"}[$__rate_interval])) * 100"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{job=~\"$job\",host=~\"$host\",name=~\"$container\",name!=\"\"}[$__rate_interval])) by (host, name) * 100",
     "legendFormat": "{{host}}: {{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{job=~\"$job\",host=~\"$host\",name=~\"$container\",name!=\"\"}",
     "legendFormat": "{{host}}: {{name}}"
    }
   ]
  },
  {
   "title": "Network Rx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{job=~\"$job\",host=~\"$host\",name=~\"$container\",name!=\"\"}[$__rate_interval])) by (host, name)",
     "legendFormat": "{{host}}: {{name}}"
    }
   ]
  },
  {
   "title": "Network Tx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{job=~\"$job\",host=~\"$host\",name=~\"$container\",name!=\"\"}[$__rate_interval])) by (host, name)",
     "legendFormat": "{{host}}: {{name}}"
    }
   ]
  }
 ]
}